import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AdminNavStatus from "./components/AdminNavStatus";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-between px-8 py-4 bg-zinc-900 border-b border-zinc-700">
          <div className="flex gap-6 items-center">
            <a href="/" className="text-xl font-bold text-white hover:text-blue-400">Leaderboard</a>
            <a href="/players" className="text-lg text-white hover:text-blue-400">Players</a>
            <a href="/games" className="text-lg text-white hover:text-blue-400">Games</a>
          </div>
          <div>
            {/* Dynamic admin/login button */}
            <AdminNavStatus />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
